# SMTP Configuration for Courson LMS
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.ssl.protocols=TLSv1.2 TLSv1.3
mail.smtp.username=hungpc1007@gmail.com
mail.smtp.password=jwua aikt koog vulp
mail.from.name=Courson LMS
app.base.url=http://localhost:8080/Courson
